{% set name = "django-todo" %}
{% set version = "2.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django-todo-{{ version }}.tar.gz
  sha256: faf17048caef44959f11b13d25a3510c0b281c12dbd45829b7a8fbe08fdd868b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=40.8.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - django >=4.0
    - factory_boy
    - titlecase
    - bleach
    - django-autocomplete-light
    - html2text

test:
  imports:
    - todo
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://django-todo.org
  summary: A multi-user, multi-group task management and assignment system for Django.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
