{% set name = "django-todo" %}
{% set version = "2.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 8cddb65e2a434323df8074c923be3d88589cfe55c74f639aea742110a0f1358f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=40.8.0
    - wheel
    - pip
  run:
    - faker
    - python >={{ python_min }}
    - django >=4.0
    - factory_boy
    - titlecase
    - bleach
    - django-autocomplete-light
    - html2text

test:
  imports:
    - todo
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://django-todo.org
  summary: A multi-user, multi-group task management and assignment system for Django.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
